### ISSUE TITLE
Dj bot: Json error

### ISSUE THREAD

**Issue by marco-bor** [SpaceManiac/discord-rs#156] opened 2017-12-15 23:40 UTC
I made a simple project with the premade dj bot.

The bot starts normally but, once i write `!dj <my_url>`, an error occurs:

`[Warning] Json(ErrorImpl { code: Message("invalid type: string \"391369516862406656\", expected a u64 or parseable string"), line: 1, column: 163 })`

Any idea on how to fix?

**Comment by marco-bor** [comment] 2017-12-16 11:58
Ok maybe the same as issue 140 but I need to check, yet

**Comment by marco-bor** [comment] 2017-12-16 12:35
Ok I found the problem in the console, but not sure why it's not working.
### Fail
``` bash
$ youtube-dl -f webm[abr>0]/bestaudio/best --no-playlist --print-json --skip-download https://www.youtube.com/watch?v=SYcmf6TKOFE
bash: 0]/bestaudio/best: No such file or directory
```

### Ok
``` bash
$ youtube-dl -f "webm[abr>0]/bestaudio/best" --no-playlist --print-json --skip-download https://www.youtube.com/watch?v=SYcmf6TKOFE
WARNING: unable to extract uploader nickname
{"upload_date": null, "protocol": "https", "c...
```

**Comment by SpaceManiac** [comment] 2018-01-27 08:16
The json error is a duplicate of #155, the rest is just a matter of needing to quote the ">" properly and make sure your youtube-dl is up to date.

**Closed as completed by SpaceManiac** 2018-01-27 08:16 UTC
