### ISSUE TITLE
Parse timestamps using chrono crate

### ISSUE THREAD

**Issue by clarfonthey** [SpaceManiac/discord-rs#92] opened 2017-01-01 19:41 UTC
Right now all of the timestamps are listed as strings, but it'd be nice if they were all parsed using the `chrono` crate so that they could be directly read and compared.

**Comment by Xaeroxe** [comment] 2017-05-30 17:56
I'm actually already doing this in my bot, I'd be happy to make a PR if @SpaceManiac wants this feature.

**Comment by SpaceManiac** [comment] 2017-05-30 22:24
Yes, I'm interested in making this change. Feel free to open a PR.

**Comment by Xaeroxe** [comment] 2017-05-31 03:18
PR opened: https://github.com/SpaceManiac/discord-rs/pull/117

**Comment by iddm** [comment] 2017-06-20 07:22
The pr is merged but the issue is still open. I think, it should be closed. @SpaceManiac

**Closed as completed** 2017-06-20 07:26 UTC
Labels: feature
